### ISSUE TITLE
Image doesn't run on kubernetes runner

### ISSUE THREAD

**Issue by MaKaNu** [astral-sh/uv-docker-example#31]
Since a few months, we are testing gitlab-runner on a kubernetes cluster.

I tested yesterday running jobs via this uv image and got the following error:

```bash
Running with gitlab-runner 16.11.3 (f5c15f76)
  on gitlab-runner-565b49f76c-xbzw8 i1cvzxzzR, system ID: r_eRStE9NH9k85
Resolving secrets
Preparing the "kubernetes" executor 00:00
Using Kubernetes namespace: gitlab-runner
Using Kubernetes executor with image ghcr.io/astral-sh/uv:latest ...
Using attach strategy to execute scripts...
Preparing environment 00:06
Using FF_USE_POD_ACTIVE_DEADLINE_SECONDS, the Pod activeDeadlineSeconds will be set to the job timeout: 1h0m0s...
Waiting for pod gitlab-runner/runner-i1cvzxzzr-project-1392-concurrent-0-wcbo7dzg to be running, status is Pending
Waiting for pod gitlab-runner/runner-i1cvzxzzr-project-1392-concurrent-0-wcbo7dzg to be running, status is Pending
	ContainersNotReady: "containers with unready status: [build helper]"
	ContainersNotReady: "containers with unready status: [build helper]"
ERROR: Job failed (system failure): prepare environment: setting up trapping scripts on emptyDir: unable to upgrade connection: container not found ("build"). Check https://docs.gitlab.com/runner/shells/index.html#shell-profile-loading for more information
```

At first, I thought this is an issue with our cluster. I was kind of right, since the syslog dumped our nodes. But the issue remained after resetting our cluster.

So I found the following [issue](https://gitlab.com/gitlab-org/charts/gitlab-runner/-/issues/477) which describes a similiar problem and applied the solution on our nodes.

Result:

```bash
WARNING: Event retrieved from the cluster: Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown
ERROR: Job failed (system failure): prepare environment: waiting for pod running: timed out waiting for pod to start. Check https://docs.gitlab.com/runner/shells/index.html#shell-profile-loading for more information
```

I checked twice with a basic pipeline (just a few echoes and alpine). Result it works:

My uv cicd-pipeline:

```yml
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

stages:
  - test
  - build
  - package
  - release

variables:
  UV_VERSION: 0.5
  PYTHON_VERSION: 3.12
  BASE_LAYER: bookworm-slim

test_ndp_cli:
  stage: test
  image: ghcr.io/astral-sh/uv:latest
  variables:
    UV_CACHE_DIR: .uv-cache
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  script:
    - uv python install
    - uv sync --all-extras --dev
    - uv run pytest
    - uv cache prune --ci
```
